### PR TITLE
fix: support registering standalone enums

### PR DESCRIPTION
**Pull request by felixjung**
Addresses #41 

This PR addresses issues with values of standalone enums not being rendered in JSON schema output.

**Changes**

* Fix the Enumception test's expected output.
* Introduce an `enums` map in the `ProtoPackage` struct and a `registerEnum` method to populate it.
* Provide a constructor for the `ProtoPackage` struct to reduce sources of error when manually putting together the struct in different places.
* Add lookup methods for enums similar to those provided for messages.
* Ensure every files standalone enums are registered.

**TODO**

* [x] Introduce the missing `relativelyLookupNestedEnum` method.
* [x] Add more test cases around enums.

### CODE REVIEW

**Comment by felixjung** [comment]
@chrusty please feel free to recommend other approaches.

**Comment by felixjung** [comment]
Still need to work out the `EnumNestedReference` test case. probably an issue somewhere in the lookup logic.

**Comment by chrusty** [comment]
Thanks @felixjung, this is a big effort!

**Comment by felixjung** [comment]
That was quick. Thanks for making this useful plugin. 👍

**Pull request merged**
