### PR TITLE
Map support

### PR DESCRIPTION
**Pull request by chrusty**
I decided to push ahead with support for proto **maps**, but after taking another look at this repo I figured it would be a lot easier to work on if I took the time to do a bit of an overhaul:

- Removed the custom logger, switched to Logrus (why did I ever have a custom logger)
- Broke the monolithic main.go up into packages
- Much tidying

### CODE REVIEW

**Comment by chrusty** [comment]
@mier85 What do you make of this? I'll make sure to take your latest change in here once we've merged it.

**Comment by mier85** [comment]
I like the split of the components! That will make future contribution much more pleasant. 

Not a big fan of logrus as the structured logging provides no type safety and I don't like the interface. However, guess it is ok for this project.

**Comment by chrusty** [comment]
Yeah Logrus is quite heavy, but the "log" package from the stdlib is too basic.

**Comment by mier85** [comment]
personally I really like github.com/uber-go/zap

**Comment by chrusty** [comment]
Yeah zap seems alright, though the interface isn't perfect for me either.

**Pull request merged**
